//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Irlovan.Lib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Irlovan.Lib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is already running.
        /// </summary>
        public static string AlreadyRunning {
            get {
                return ResourceManager.GetString("AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttributeError:.
        /// </summary>
        public static string AttributeError {
            get {
                return ResourceManager.GetString("AttributeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute init failed:.
        /// </summary>
        public static string AttributeNotInit {
            get {
                return ResourceManager.GetString("AttributeNotInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find attribute :.
        /// </summary>
        public static string AttrNotFound {
            get {
                return ResourceManager.GetString("AttrNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientCount:.
        /// </summary>
        public static string ClientCount {
            get {
                return ResourceManager.GetString("ClientCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Load Config File,Application Open Failed!.
        /// </summary>
        public static string ConfigFileError {
            get {
                return ResourceManager.GetString("ConfigFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Reject.
        /// </summary>
        public static string ConnectionReject {
            get {
                return ResourceManager.GetString("ConnectionReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Connected.
        /// </summary>
        public static string ConnectionSuccess {
            get {
                return ResourceManager.GetString("ConnectionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseConnectFailed:.
        /// </summary>
        public static string DatabaseConnectFailed {
            get {
                return ResourceManager.GetString("DatabaseConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseInitFailed:.
        /// </summary>
        public static string DatabaseInitFailed {
            get {
                return ResourceManager.GetString("DatabaseInitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseKeyExist.
        /// </summary>
        public static string DatabaseKeyExist {
            get {
                return ResourceManager.GetString("DatabaseKeyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t convert type.
        /// </summary>
        public static string DataTypeConvertFail {
            get {
                return ResourceManager.GetString("DataTypeConvertFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  can&apos;t fine address .
        /// </summary>
        public static string DriverAddrNotFound {
            get {
                return ResourceManager.GetString("DriverAddrNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriverConnectedSuccess.
        /// </summary>
        public static string DriverConnected {
            get {
                return ResourceManager.GetString("DriverConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriverConnectFail.
        /// </summary>
        public static string DriverConnectFail {
            get {
                return ResourceManager.GetString("DriverConnectFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver data already exist:.
        /// </summary>
        public static string DriverDataExist {
            get {
                return ResourceManager.GetString("DriverDataExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  can&apos;t find data .
        /// </summary>
        public static string DriverDataNotFound {
            get {
                return ResourceManager.GetString("DriverDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No source for Driver.
        /// </summary>
        public static string DriverNoSource {
            get {
                return ResourceManager.GetString("DriverNoSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriverReConnected.
        /// </summary>
        public static string DriverReConnected {
            get {
                return ResourceManager.GetString("DriverReConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriverShutDown.
        /// </summary>
        public static string DriverShutDown {
            get {
                return ResourceManager.GetString("DriverShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileNotExist.
        /// </summary>
        public static string FileNotExist {
            get {
                return ResourceManager.GetString("FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler Not Found:.
        /// </summary>
        public static string HandlerNotFound {
            get {
                return ResourceManager.GetString("HandlerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The languge you select is not supported.
        /// </summary>
        public static string LanguageUnsupported {
            get {
                return ResourceManager.GetString("LanguageUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started to listen on port :.
        /// </summary>
        public static string ListenPort {
            get {
                return ResourceManager.GetString("ListenPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error happend when Listen on port :.
        /// </summary>
        public static string ListenPortFailed {
            get {
                return ResourceManager.GetString("ListenPortFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadGUIFailed.
        /// </summary>
        public static string LoadGUIFailed {
            get {
                return ResourceManager.GetString("LoadGUIFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadRecorderFail:.
        /// </summary>
        public static string LoadRecorderFail {
            get {
                return ResourceManager.GetString("LoadRecorderFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginFailed.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginSuccess.
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogRecorderConnected.
        /// </summary>
        public static string LogRecorderConnected {
            get {
                return ResourceManager.GetString("LogRecorderConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModbusDeviceInitFailed.
        /// </summary>
        public static string ModbusDeviceInitFailed {
            get {
                return ResourceManager.GetString("ModbusDeviceInitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModeSubcribeFailed.
        /// </summary>
        public static string ModeSubcribeFailed {
            get {
                return ResourceManager.GetString("ModeSubcribeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleHandlerSourceLoadFailed.
        /// </summary>
        public static string ModuleHandlerSourceLoadFailed {
            get {
                return ResourceManager.GetString("ModuleHandlerSourceLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID attribute not found.
        /// </summary>
        public static string NoID {
            get {
                return ResourceManager.GetString("NoID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name attribute not found.
        /// </summary>
        public static string NoName {
            get {
                return ResourceManager.GetString("NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoPortsListen!Please Choose a port for the project in config file.
        /// </summary>
        public static string NoPortsListen {
            get {
                return ResourceManager.GetString("NoPortsListen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database not found.
        /// </summary>
        public static string NoRealtimeData {
            get {
                return ResourceManager.GetString("NoRealtimeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder Name attribute must be set first.
        /// </summary>
        public static string NoRecorderName {
            get {
                return ResourceManager.GetString("NoRecorderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string NoticeWindow_Confirm {
            get {
                return ResourceManager.GetString("NoticeWindow_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        public static string NoticeWindow_Title {
            get {
                return ResourceManager.GetString("NoticeWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification ID already exist.
        /// </summary>
        public static string NotificationIDExist {
            get {
                return ResourceManager.GetString("NotificationIDExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Resource Not Found.
        /// </summary>
        public static string NotificationNoResource {
            get {
                return ResourceManager.GetString("NotificationNoResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPC Init Error : this happened when server is initalize,but the opc failed.
        /// </summary>
        public static string OPCInitFailed {
            get {
                return ResourceManager.GetString("OPCInitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageRecorderFailed.
        /// </summary>
        public static string PageRecorderFailed {
            get {
                return ResourceManager.GetString("PageRecorderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Terminated.
        /// </summary>
        public static string ProgramExit {
            get {
                return ResourceManager.GetString("ProgramExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project is already runing :.
        /// </summary>
        public static string ProjectAlreadyRuning {
            get {
                return ResourceManager.GetString("ProjectAlreadyRuning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find project folder.
        /// </summary>
        public static string ProjectNotFound {
            get {
                return ResourceManager.GetString("ProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadonlyPropertyError.
        /// </summary>
        public static string ReadonlyPropertyError {
            get {
                return ResourceManager.GetString("ReadonlyPropertyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadRecorderFailed:.
        /// </summary>
        public static string ReadRecorderFailed {
            get {
                return ResourceManager.GetString("ReadRecorderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder handler runing failed: .
        /// </summary>
        public static string RecorderHandlerFailed {
            get {
                return ResourceManager.GetString("RecorderHandlerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder name already exist.
        /// </summary>
        public static string RecorderNameExist {
            get {
                return ResourceManager.GetString("RecorderNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find resource for recorder.
        /// </summary>
        public static string RecorderNoResource {
            get {
                return ResourceManager.GetString("RecorderNoResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecorderTypeNotSupported:.
        /// </summary>
        public static string RecorderTypeNotSupported {
            get {
                return ResourceManager.GetString("RecorderTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterInitFailed:.
        /// </summary>
        public static string RegisterInitFailed {
            get {
                return ResourceManager.GetString("RegisterInitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScriptError:.
        /// </summary>
        public static string ScriptError {
            get {
                return ResourceManager.GetString("ScriptError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script System Failed:.
        /// </summary>
        public static string ScriptFail {
            get {
                return ResourceManager.GetString("ScriptFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script System Init Success.
        /// </summary>
        public static string ScriptLoad {
            get {
                return ResourceManager.GetString("ScriptLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script file not found:.
        /// </summary>
        public static string ScriptNotFound {
            get {
                return ResourceManager.GetString("ScriptNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerStart.
        /// </summary>
        public static string ServerStart {
            get {
                return ResourceManager.GetString("ServerStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLDatabaseConnected.
        /// </summary>
        public static string SQLDatabaseConnected {
            get {
                return ResourceManager.GetString("SQLDatabaseConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLDatabaseConnectedFail.
        /// </summary>
        public static string SQLDatabaseConnectedFail {
            get {
                return ResourceManager.GetString("SQLDatabaseConnectedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatisticData Not Found:.
        /// </summary>
        public static string StatisticDataNotFound {
            get {
                return ResourceManager.GetString("StatisticDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatisticRecorderError:.
        /// </summary>
        public static string StatisticRecorderError {
            get {
                return ResourceManager.GetString("StatisticRecorderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserManagerEditFailed.
        /// </summary>
        public static string UserManagerEditFailed {
            get {
                return ResourceManager.GetString("UserManagerEditFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserManagerLogin.
        /// </summary>
        public static string UserManagerLogin {
            get {
                return ResourceManager.GetString("UserManagerLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserManagerLoginFail.
        /// </summary>
        public static string UserManagerLoginFail {
            get {
                return ResourceManager.GetString("UserManagerLoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WriteDataFailed.
        /// </summary>
        public static string WriteDataFailed {
            get {
                return ResourceManager.GetString("WriteDataFailed", resourceCulture);
            }
        }
    }
}
